name: ChatGPT Crawler

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run_crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - run: |
          pip install --upgrade pip
          pip install tweepy
      - run: python chatgpt_crawler.py
        env: 
          consumer_key: ${{secrets.API_KEY}}
          consumer_secret: ${{secrets.API_KEY_SECRET}}
          access_token: ${{secrets.ACCESS_TOKEN}}
          access_token_secret: ${{secrets.ACCESS_TOKEN_SECRET}}
